#!/bin/bash -e

apt update
apt upgrade
apt install -y sudo

useradd -m -s /bin/bash emu
passwd emu
usermod -aG sudo emu
usermod -aG input emu

apt install -y mc
apt install -y gpm
apt install -y alsa-utils

# openbox
cp -r .config /home/emu/
chown -R emu:emu /home/emu/.config
apt install -y sudo xorg chromium openbox lightdm gnome-terminal

cat << EOF >> /etc/lightdm/lightdm.conf
[SeatDefaults]
autologin-user=emu
user-session=openbox
EOF

#FS-UAE
apt install -y curl
echo 'deb http://download.opensuse.org/repositories/home:/FrodeSolheim:/stable/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/home:FrodeSolheim:stable.list
curl -fsSL https://download.opensuse.org/repositories/home:FrodeSolheim:stable/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_FrodeSolheim_stable.gpg > /dev/null
apt update
apt install -y fs-uae fs-uae-launcher fs-uae-arcade
cd $HOME/mini-emu-x11/
mkdir -p FS-UAE/Floppies
cd FS-UAE/Floppies
wget http://ftp.amigascne.org/pub/amiga/Groups/S/Spaceballs/Spaceballs-StateOfTheArt.dms
cd ../..
cp -r FS-UAE /home/emu/
chown -R emu:emu /home/emu/FS-UAE

apt install -y libsdl2-net-2.0-0
apt install -y libopusfile0
cd $HOME/mini-emu-x11/
wget https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.78.1/dosbox-staging-linux-v0.78.1.tar.xz
cd /home/emu/
tar xf $HOME/mini-emu-x11/dosbox-staging-linux-v0.78.1.tar.xz
chown -R emu:emu dosbox-staging-linux-v0.78.1

VICE_VER=3.6.1
sudo apt install -y flex bison xa65 dos2unix libsdl2-dev libsdl2-image-dev libpng-dev build-essential
cd $HOME/mini-emu-x11/
wget https://altushost-swe.dl.sourceforge.net/project/vice-emu/releases/vice-${VICE_VER}.tar.gz
tar xf vice-${VICE_VER}.tar.gz
cd vice-${VICE_VER}/
#as we have alsa, we do not need pulse
./configure --without-pulse --disable-pdf-docs
make -j16
make install

echo "REBOOT! Do not panic."
sleep  2
reboot
